[package]
name = "protocol"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
thiserror = { workspace = true }
bincode = { workspace = true, features = ["serde", "derive"] }
bytes = { workspace = true, features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
